// This file was auto-generated by Fern from our API Definition.

package sandboxes

import (
	context "context"
	fmt "fmt"
	vellum "github.com/vellum-ai/terraform-provider-vellum/internal/vellum"
	core "github.com/vellum-ai/terraform-provider-vellum/internal/vellum/core"
	option "github.com/vellum-ai/terraform-provider-vellum/internal/vellum/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Upserts a new scenario for a sandbox, keying off of the optionally provided scenario id.
//
// If an id is provided and has a match, the scenario will be updated. If no id is provided or no match
// is found, a new scenario will be appended to the end.
//
// Note that a full replacement of the scenario is performed, so any fields not provided will be removed
// or overwritten with default values.
func (c *Client) UpsertSandboxScenario(
	ctx context.Context,
	// A UUID string identifying this sandbox.
	id string,
	request *vellum.UpsertSandboxScenarioRequestRequest,
	opts ...option.RequestOption,
) (*vellum.SandboxScenario, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://api.vellum.ai"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := fmt.Sprintf(baseURL+"/"+"v1/sandboxes/%v/scenarios", id)

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *vellum.SandboxScenario
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodPost,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Request:     request,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Deletes an existing scenario from a sandbox, keying off of the provided scenario id.
func (c *Client) DeleteSandboxScenario(
	ctx context.Context,
	// A UUID string identifying this sandbox.
	id string,
	// An id identifying the scenario that you'd like to delete
	scenarioId string,
	opts ...option.RequestOption,
) error {
	options := core.NewRequestOptions(opts...)

	baseURL := "https://api.vellum.ai"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := fmt.Sprintf(baseURL+"/"+"v1/sandboxes/%v/scenarios/%v", id, scenarioId)

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodDelete,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
		},
	); err != nil {
		return err
	}
	return nil
}
