// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_vellum

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func VellumProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type VellumModel struct {
}
