// This file was auto-generated by Fern from our API Definition.

package vellum

type UpsertTestSuiteTestCaseRequest struct {
	UpsertTestSuiteTestCaseRequestId *string                              `json:"id,omitempty" url:"id,omitempty"`
	Label                            *string                              `json:"label,omitempty" url:"label,omitempty"`
	InputValues                      []*NamedTestCaseVariableValueRequest `json:"input_values,omitempty" url:"input_values,omitempty"`
	EvaluationValues                 []*NamedTestCaseVariableValueRequest `json:"evaluation_values,omitempty" url:"evaluation_values,omitempty"`
}
