// This file was auto-generated by Fern from our API Definition.

package vellum

type TestSuiteRunCreateRequest struct {
	// The ID of the Test Suite to run
	TestSuiteId string `json:"test_suite_id" url:"test_suite_id"`
	// Configuration that defines how the Test Suite should be run
	ExecConfig *TestSuiteRunExecConfigRequest `json:"exec_config,omitempty" url:"exec_config,omitempty"`
}

type TestSuiteRunsListExecutionsRequest struct {
	// Number of results to return per page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// The initial index from which to return the results.
	Offset *int `json:"-" url:"offset,omitempty"`
}
