// This file was auto-generated by Fern from our API Definition.

package client

import (
	http "net/http"
	core "terraform-provider-vellum/internal/sdk/core"
	documentindexes "terraform-provider-vellum/internal/sdk/documentindexes"
	mlmodels "terraform-provider-vellum/internal/sdk/mlmodels"
	option "terraform-provider-vellum/internal/sdk/option"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	DocumentIndexes *documentindexes.Client
	MlModels        *mlmodels.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:          options.ToHeader(),
		DocumentIndexes: documentindexes.NewClient(opts...),
		MlModels:        mlmodels.NewClient(opts...),
	}
}
